version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
      target: server-runtime
    container_name: a1-studylink-server
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=5000
      # 프런트엔드가 접근 가능한 오리진 목록
      - CORS_ORIGIN=http://localhost:3000,http://client:3000
    volumes:
      - ./server/data:/app/data
    expose:
      - "5000"
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
      target: client-runtime
    container_name: a1-studylink-client
    depends_on:
      - server
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

networks:
  default:
    name: a1-studylink-net
